### ISSUE TITLE
go run main.go 实例的时候出现问题

### ISSUE THREAD

**Issue by ftx456789** [commis/fabric-sdk-go-gm#1]
failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve
请问怎么解决呢

**Comment by commis** [comment]
客户端的网络配置文件错误，BCCP中的hash配置错误。发自我的华为手机-------- 原始邮件 --------发件人： ftx456789 <notifications@github.com>日期： 2020年3月2日周一 12:12收件人： commis/fabric-sdk-go-gm <fabric-sdk-go-gm@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve

请问怎么解决呢

**Comment by ftx456789** [comment]
我yaml文件中这样配置后
BCCSP:
&nbsp; &nbsp; security:
&nbsp; &nbsp; &nbsp;enabled: true
&nbsp; &nbsp; &nbsp;default:
&nbsp; &nbsp; &nbsp; provider: "GM"
&nbsp; &nbsp; &nbsp;hashAlgorithm: "GMSM3"
&nbsp; &nbsp; &nbsp;softVerify: true
&nbsp; &nbsp; &nbsp;level: 256

出现
bccsp gm keyimport pk is *sm2.PublicKey [fabsdk/fab] 2020/03/06 12:55:46 UTC - peer.(*peerEndorser).sendProposal -&gt; ERRO process proposal failed [rpc error: code = Unknown desc = access denied: channel [mychannel] creator org [Org1MSP]]
could not get chConfig cache reference: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [localhost:7051]: gRPC Transport Status Code: (2) Unknown. Description: access denied: channel [mychannel] creator org [Org1MSP]exit status 255

这样的错误，实例是对first-network进行查询，希望大佬能告知，fabric国密改造是按照https://github.com/dddengyunjie/fabric
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bing Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 晚上8:44
收件人:&nbsp;"commis/fabric-sdk-go-gm"<fabric-sdk-go-gm@noreply.github.com&gt;;
抄送:&nbsp;"冯天祥"<469257973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)



客户端的网络配置文件错误，BCCP中的hash配置错误。发自我的华为手机-------- 原始邮件 --------发件人： ftx456789 <notifications@github.com&gt;日期： 2020年3月2日周一 12:12收件人： commis/fabric-sdk-go-gm <fabric-sdk-go-gm@noreply.github.com&gt;抄送： Subscribed <subscribed@noreply.github.com&gt;主    题： [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve 
 请问怎么解决呢

**Comment by commis** [comment]
客户端策略配置文件有问题，无法访问orderer节点，晚点发给你正确的配置。发自我的华为手机-------- 原始邮件 --------发件人： ftx456789 <notifications@github.com>日期： 2020年3月6日周五 20:57收件人： commis/fabric-sdk-go-gm <fabric-sdk-go-gm@noreply.github.com>抄送： Bing Xu <hbcqxb@163.com>, Comment <comment@noreply.github.com>主    题： Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)我yaml文件中这样配置后



BCCSP:



&nbsp; &nbsp; security:



&nbsp; &nbsp; &nbsp;enabled: true



&nbsp; &nbsp; &nbsp;default:



&nbsp; &nbsp; &nbsp; provider: "GM"



&nbsp; &nbsp; &nbsp;hashAlgorithm: "GMSM3"



&nbsp; &nbsp; &nbsp;softVerify: true



&nbsp; &nbsp; &nbsp;level: 256







出现



bccsp gm keyimport pk is *sm2.PublicKey [fabsdk/fab] 2020/03/06 12:55:46 UTC - peer.(*peerEndorser).sendProposal -&gt; ERRO process proposal failed [rpc error: code = Unknown desc = access denied: channel [mychannel] creator org [Org1MSP]]



could not get chConfig cache reference: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [localhost:7051]: gRPC Transport Status Code: (2) Unknown. Description: access denied: channel [mychannel] creator org [Org1MSP]exit status 255







这样的错误，实例是对first-network进行查询，希望大佬能告知，fabric国密改造是按照https://github.com/dddengyunjie/fabric



------------------&nbsp;原始邮件&nbsp;------------------



发件人:&nbsp;"Bing Xu"<notifications@github.com&gt;;



发送时间:&nbsp;2020年3月6日(星期五) 晚上8:44



收件人:&nbsp;"commis/fabric-sdk-go-gm"<fabric-sdk-go-gm@noreply.github.com&gt;;



抄送:&nbsp;"冯天祥"<469257973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;



主题:&nbsp;Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)















客户端的网络配置文件错误，BCCP中的hash配置错误。发自我的华为手机-------- 原始邮件 --------发件人： ftx456789 <notifications@github.com&gt;日期： 2020年3月2日周一 12:12收件人： commis/fabric-sdk-go-gm <fabric-sdk-go-gm@noreply.github.com&gt;抄送： Subscribed <subscribed@noreply.github.com&gt;主    题： [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve 



 请问怎么解决呢

**Comment by ftx456789** [comment]
感谢大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bing Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 晚上9:04
收件人:&nbsp;"commis/fabric-sdk-go-gm"<fabric-sdk-go-gm@noreply.github.com&gt;;
抄送:&nbsp;"冯天祥"<469257973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)



客户端策略配置文件有问题，无法访问orderer节点，晚点发给你正确的配置。发自我的华为手机-------- 原始邮件 --------发件人： ftx456789 <notifications@github.com&gt;日期： 2020年3月6日周五 20:57收件人： commis/fabric-sdk-go-gm <fabric-sdk-go-gm@noreply.github.com&gt;抄送： Bing Xu <hbcqxb@163.com&gt;, Comment <comment@noreply.github.com&gt;主    题： Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)我yaml文件中这样配置后 
 
 BCCSP: 
 
 &amp;nbsp; &amp;nbsp; security: 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;enabled: true 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;default: 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; provider: "GM" 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;hashAlgorithm: "GMSM3" 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;softVerify: true 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;level: 256 
 
 
 
 出现 
 
 bccsp gm keyimport pk is *sm2.PublicKey [fabsdk/fab] 2020/03/06 12:55:46 UTC - peer.(*peerEndorser).sendProposal -&amp;gt; ERRO process proposal failed [rpc error: code = Unknown desc = access denied: channel [mychannel] creator org [Org1MSP]] 
 
 could not get chConfig cache reference: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [localhost:7051]: gRPC Transport Status Code: (2) Unknown. Description: access denied: channel [mychannel] creator org [Org1MSP]exit status 255 
 
 
 
 这样的错误，实例是对first-network进行查询，希望大佬能告知，fabric国密改造是按照https://github.com/dddengyunjie/fabric 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 
 发件人:&amp;nbsp;"Bing Xu"<notifications@github.com&amp;gt;; 
 
 发送时间:&amp;nbsp;2020年3月6日(星期五) 晚上8:44 
 
 收件人:&amp;nbsp;"commis/fabric-sdk-go-gm"<fabric-sdk-go-gm@noreply.github.com&amp;gt;; 
 
 抄送:&amp;nbsp;"冯天祥"<469257973@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 
 主题:&amp;nbsp;Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1) 
 
 
 
 
 
 
 
 客户端的网络配置文件错误，BCCP中的hash配置错误。发自我的华为手机-------- 原始邮件 --------发件人： ftx456789 <notifications@github.com&amp;gt;日期： 2020年3月2日周一 12:12收件人： commis/fabric-sdk-go-gm <fabric-sdk-go-gm@noreply.github.com&amp;gt;抄送： Subscribed <subscribed@noreply.github.com&amp;gt;主    题： [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve  
 
  请问怎么解决呢

**Comment by commis** [comment]
可以在yaml文件的尾部增加：
entityMatchers:
  orderer:
    - pattern: (\w+).example.(\w+)
      urlSubstitutionExp: grpc://localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.example.com
      mappedHost: orderer.example.com

附件是我自己测试用的配置文件，供参考。




hbcqxb@163.com
 
发件人： ftx456789
发送时间： 2020-03-02 12:12
收件人： commis/fabric-sdk-go-gm
抄送： Subscribed
主题： [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)
failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve
请问怎么解决呢

**Comment by ftx456789** [comment]
大佬github的回复邮件看不到附件，能麻烦您再发一次嘛，我的邮箱是469257973@qq.com,再次感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bing Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 晚上10:49
收件人:&nbsp;"commis/fabric-sdk-go-gm"<fabric-sdk-go-gm@noreply.github.com&gt;;
抄送:&nbsp;"冯天祥"<469257973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1)



可以在yaml文件的尾部增加： 
 entityMatchers: 
   orderer: 
     - pattern: (\w+).example.(\w+) 
       urlSubstitutionExp: grpc://localhost:7050 
       sslTargetOverrideUrlSubstitutionExp: orderer.example.com 
       mappedHost: orderer.example.com 
 
 附件是我自己测试用的配置文件，供参考。 
 
 
 
 
 hbcqxb@163.com 
   
 发件人： ftx456789 
 发送时间： 2020-03-02 12:12 
 收件人： commis/fabric-sdk-go-gm 
 抄送： Subscribed 
 主题： [commis/fabric-sdk-go-gm] go run main.go 实例的时候出现问题 (#1) 
 failed to create SDK: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to network config: failed to load orderer network config: certificate parsing failed: x509: unsupported elliptic curve 
 请问怎么解决呢

**Comment by commis** [comment]
如果使用https://github.com/dddengyunjie/fabric 启动支持国密的网络，需要修改代码如下代码变更Hash算法：
fabric-sdk-go/pkg/fab/signingmgr/signingmgr.go
第32行：cryptosuite.GetSM3Opts()  改成：cryptosuite.GetSHA256Opts()

另外：必须要确保网络启动是走的国密分支，可以查看启动网络脚本的日志：
2020-03-07 18:07:44.049 UTC [viperutil] EnhancedExactUnmarshalKey -> DEBU 01a **map[peer.BCCSP:map[Default:GM PKCS11:map[FileKeyStore:map[KeyStore:<nil>] Hash:<nil> Label:<nil> Library:<nil> Pin:<nil> Security:<nil>] SW:map[FileKeyStore:map[KeyStore:] Hash:GMSM3 Security:256]]]**
2020-03-07 18:07:44.050 UTC [bccsp_gm] openKeyStore -> DEBU 01b KeyStore opened at [/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore]...done
2020-03-07 18:07:44.050 UTC [bccsp] initBCCSP -> DEBU 01c **Initialize BCCSP [GM]**

**Comment by commis** [comment]
**客户端使用问题一：**
2020-03-08 02:47:13.576 CST [httpSvr.core.chaincode] QueryChainCode -> ERRO 007 failed to query funds : Transaction processing for endorser [peer0.org2.example.com:9051]: Endorser Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection timed out [peer0.org2.example.com:9051]
2020-03-08 02:47:13.576 CST [httpSvr.core.common] WriteFailedResponse -> ERRO 008 Error: {"code":1001,"data":null,"message":"Transaction processing for endorser [peer0.org2.example.com:9051]: Endorser Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection timed out [peer0.org2.example.com:9051]"}
类似这样的错误，节点连接超时错误。

**解决方案：**
在fabric-network.yaml的配置文件中添加配置：
entityMatchers:
  orderer:
    - pattern: (\w+).example.(\w+)
      urlSubstitutionExp: grpc://127.0.0.1:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.example.com
      mappedHost: orderer.example.com
  peer:
    - pattern: (\w+).(\w+).example.(\w+)
      urlSubstitutionExp: grpc://127.0.0.1:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer0.org1.example.com

    - pattern: (\w+).(\w+).example.(\w+)
      urlSubstitutionExp: grpc://127.0.0.1:9051
      sslTargetOverrideUrlSubstitutionExp: peer0.org2.example.com
      mappedHost: peer0.org2.example.com

**Comment by commis** [comment]
**客户端使用问题二：**
 [fabsdk/fab] 2020/03/07 18:54:38 UTC - n/a -> ERRO process proposal failed [rpc error: code = Unknown desc = access denied: channel [mychannel] creator org [Org1MSP]]
2020-03-08 02:54:38.757 CST [httpSvr.core.common] setupChannelClient -> CRIT 003 create channel channelClient error: event service creation failed: could not get chConfig cache reference: QueryBlockConfig failed: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [127.0.0.1:7051]: gRPC Transport Status Code: (2) Unknown. Description: access denied: channel [mychannel] creator org [Org1MSP]

类似这样的错误，可以查看对应Peer节点的日志：
2020-03-07 18:54:38.756 UTC [protoutils] ValidateProposalMessage -> WARN 18b channel [mychannel]: **creator's signature over the proposal is not valid: The signature is invalid**
2020-03-07 18:54:38.756 UTC [comm.grpc.server] 1 -> INFO 18c unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.request_deadline=2020-03-07T18:57:38.743Z grpc.peer_address=172.28.0.1:47224 error="access denied: channel [mychannel] creator org [Org1MSP]" grpc.code=Unknown grpc.call_duration=5.742697ms
无效的签名，可能是客户端使用的签名算法和fabric网络使用的签名算法不一致。

可参考 https://github.com/commis/fabric-sdk-go-gm/issues/1#issuecomment-596125927 修改客户端使用的签名算法。

**Comment by commis** [comment]
经过本人测试，发现 https://github.com/dddengyunjie/fabric 代码编译的镜像默认启动网络不是国密，需要做以下代码的修改才能够支持默认国密，并能很好的配合本sdk开发应用端。

```
sampleconfig/orderer.yaml
第124行：Default: GM
第131行：Hash: GMSM3

sampleconfig/core.yaml
第272行，第278行，和上面一样的修改。

msp/configbuilder.go
第137行修改：
if bccspConfig.ProviderName == "SW" || bccspConfig.ProviderName == "GM" {

msp/identities.go
第193行的getHashOpt函数修改：
func (id *identity) getHashOpt(hashFamily string) (bccsp.HashOpts, error) {
	switch hashFamily {
	case bccsp.SHA3:
		return bccsp.GetHashOpt(bccsp.SHA3_256)
	case bccsp.SHA2:
		return bccsp.GetHashOpt(bccsp.SHA256)
	case bccsp.GMSM3: //主要是增加这个case
		return bccsp.GetHashOpt(bccsp.GMSM3)
	}
	return nil, errors.Errorf("hash familiy not recognized [%s]", hashFamily)
}

bccsp/factory/nopkcs11.go
第46行修改：config.ProviderName = "GM"

common/tools/idemixgen/idemixgen.go
import 里面删除crypto/x509
"gopkg.in/alecthomas/kingpin.v2"
改为：
kingpin "gopkg.in/alecthomas/kingpin.v2"

第70行修改：
//encodedRevocationPK, err := x509.MarshalPKIXPublicKey(revocationKey.Public())
encodedRevocationPK, err := sm2.MarshalPKIXPublicKey(revocationKey.Public())
```

**Comment by csquan** [comment]
https://github.com/dddengyunjie/fabric将代码按照上述修改后，运行order报错：Invalid DER for channel testchainid

**Comment by csquan** [comment]
按照上面修改，并debug到代码里解决了Invalid DER for channel testchainid错误后，实例化出错：failed to invoke chaincode name:"lscc" , error: container exited with 2 
ddd代码貌似不支持tls，一大堆错误，为什么开源，无语。
